name = "«rust-lean-models»"
defaultTargets = ["RustLeanModels"]

[leanOptions]
pp.unicode.fun = true

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "0f3e143"

[[lean_lib]]
name = "RustLeanModels"
